# Generated by Django 5.0.3 on 2024-11-21 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.labtest', verbose_name='examen'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.order', verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.affiliation'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='orders',
            field=models.ManyToManyField(related_name='invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.tax'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.bank', verbose_name='banco'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='orders.orderinvoice'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='orders.labtest'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_parameters', to='orders.parameter'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.patient'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='orders.patient'),
        ),
        migrations.AddField(
            model_name='patientaffiliation',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.affiliation'),
        ),
        migrations.AddField(
            model_name='patientaffiliation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='orders.patient'),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_values', to='orders.parameter'),
        ),
        migrations.AddField(
            model_name='result',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_test_result', to='orders.labtest', verbose_name='examen'),
        ),
        migrations.AddField(
            model_name='result',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='orders.order', verbose_name='orden'),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultvalues',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_values', to='orders.resultvalues'),
        ),
        migrations.AddField(
            model_name='resultvalues',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_values', to='orders.result', verbose_name='resultado'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.sample'),
        ),
    ]
