# Generated by Django 5.0.3 on 2024-11-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'pendiente'), ('Procesado', 'Procesado'), ('Parcialmente procesado', 'Parcialmente procesado'), ('Borrador', 'borrador'), ('Anulado', 'anulado')], default='Pendiente', max_length=35, verbose_name='estado'),
        ),
    ]
