# Generated by Django 5.0.3 on 2024-11-21 01:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Anulado', 'Anulado')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='monto pagado')),
                ('due_date', models.DateField(default=datetime.datetime.now, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('hour', models.TimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'cuenta por pagar',
                'verbose_name_plural': 'cuentas por pagar',
                'db_table': 'account_payable',
                'permissions': (('view_account_payable', 'Ver cuentas por pagar'), ('make_payments', 'Realizar pagos')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'detalle de orden de compra',
                'verbose_name_plural': 'detalle de ordenes de compras',
                'db_table': 'purchase_order_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('request_date', models.DateField(default=datetime.datetime.now, verbose_name='fecha de solicitud')),
                ('required_date', models.DateField(default=datetime.datetime.now, verbose_name='fecha requerida')),
                ('request_hour', models.TimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Convertido en Orden de Compra', 'Convertido en Orden de Compra'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Devuelto', 'Devuelto'), ('Borrador', 'Borrador'), ('Anulado', 'Anulado')], default='Pendiente', max_length=35)),
            ],
            options={
                'verbose_name': 'requisición de compra',
                'verbose_name_plural': 'requisiciones de compras',
                'db_table': 'purchase_requisition',
                'permissions': (('view_purchase_requisition', 'Ver requisiciones de compras'), ('add_purchase_requisition', 'Crear requisición de compra'), ('delete_purchase_requisition', 'Eliminar requisición de compra'), ('change_purchase_requisition', 'Modificar requisición de compra')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('approved_amount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'detalle de requisición de compra',
                'verbose_name_plural': 'detalle de requisiciones de compras',
                'db_table': 'purchase_requisition_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReceivingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reception_date', models.DateField(default=datetime.datetime.now)),
                ('reception_hour', models.TimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Parcialmente Recibido', 'Parcialmente Recibido'), ('Completamente Recibido', 'Completamente Recibido'), ('Anulado', 'Anulado')], max_length=50)),
            ],
            options={
                'verbose_name': 'recepción de ordenes',
                'verbose_name_plural': 'rececion  de compras',
                'db_table': 'receiving_order',
                'permissions': (('view_receiving_order', 'Acceder al módulo de recepción de órdenes de compra'), ('add_receiving_order', 'Crear recepción de orden de compra'), ('disable_receiving_order', 'Anular recepción de orden de compra'), ('change_receiving_order', 'Modificar recepción de orden de compra')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReceivingOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('expected_quantity', models.PositiveIntegerField(verbose_name='cantidad esperada')),
                ('received_quantity', models.PositiveIntegerField(verbose_name='cantidad recibida')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto')], default='Completo', max_length=35)),
            ],
            options={
                'verbose_name': 'detalle de recepción de orden de compra',
                'verbose_name_plural': 'detalles de receciones ordenes de compras',
                'db_table': 'receiving_order_detail',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=90, unique=True, verbose_name='nombre comercial')),
                ('legal_name', models.CharField(max_length=90, unique=True, verbose_name='razón social')),
                ('rif', models.CharField(max_length=30, unique=True, verbose_name='RIF')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='número de teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=60)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='límite de crédito')),
                ('credit_days', models.PositiveIntegerField(default=15)),
                ('postal_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='código postal')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'supplier',
                'permissions': (('view_supplier', 'Ver proveedores'), ('add_supplier', 'Crear proveedor'), ('delete_supplier', 'Eliminar proveedor'), ('change_supplier', 'Modificar proveedor')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountPayablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=14, verbose_name='abono')),
                ('payment_method', models.CharField(choices=[('Efectivo', 'efectivo'), ('Pago movil', 'pago movil'), ('Transferencia', 'transferencia'), ('Tarjeta de débito', 'tarjeta de debito'), ('Tarjeta de crédito', 'tarjeta de crédito'), ('Divisa', 'divisa'), ('Cheque', 'cheque'), ('Otros', 'otros')], default='Efectivo', max_length=20, verbose_name='método de pago')),
                ('payment_ref', models.CharField(blank=True, max_length=50, verbose_name='número de referencia')),
                ('payment_date', models.DateField(auto_now=True, verbose_name='fecha de pago')),
                ('payment_time', models.TimeField(auto_now=True, verbose_name='hora de pago')),
                ('comment', models.CharField(blank=True, max_length=150, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable_payments', to='procurement.accountpayable')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.bank', verbose_name='banco')),
            ],
            options={
                'verbose_name': 'pago de cuenta por pagar',
                'verbose_name_plural': 'pagos de cuentas por pagar',
                'db_table': 'account_payable_payment',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada'), ('Parcialmente Recibido', 'Parcialmente Recibido'), ('Completamente Recibido', 'Completamente Recibido'), ('Anulada', 'Anulada'), ('Borrador', 'Borrador')], default='Pendiente', max_length=35)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('secondary_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='total en divisa')),
                ('main_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='total principal')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='monto pagado')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_date', models.DateField(default=datetime.datetime.now)),
                ('order_hour', models.TimeField(auto_now=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(null=True)),
                ('payment_term', models.PositiveIntegerField(default=1, verbose_name='plazo de pago')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_purchase_orders', to='configuration.laboratory')),
                ('main_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.currency', verbose_name='moneda principal')),
                ('secondary_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.currency', verbose_name='moneda secundaria')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.tax')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ordenes de compras',
                'db_table': 'purchase_order',
                'permissions': (('view_purchase_order', 'Ver ordenes de compras'), ('add_purchase_order', 'Crear orden de compra'), ('delete_purchase_order', 'Eliminar orden de compra'), ('change_purchase_order', 'Modificar orden de compra')),
                'default_permissions': (),
            },
        ),
    ]
