# Generated by Django 5.0.3 on 2024-11-21 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('inventory', '0002_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_account_payable', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchaseorderdetail',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_detail', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_requisition', to='configuration.laboratory'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisition', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchaserequisitiondetail',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_detail_set', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='receivingorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_order', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='receivingorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivingorderdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='receivingorderdetail',
            name='receiving_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_order_detail', to='procurement.receivingorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_purchase_orders', to='procurement.supplier'),
        ),
    ]
