# Generated by Django 5.0.3 on 2024-11-21 01:33

import apps.configuration.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'bancos',
                'db_table': 'bank',
                'permissions': (('view_bank', 'Acceder al modulo de bancos'), ('add_banck', 'Crear banco'), ('delete_bank', 'Eliminar banco'), ('change_bank', 'Modificar banco')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('document', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('local_phone', models.CharField(max_length=11, unique=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('manager', models.CharField(max_length=70)),
                ('cedula', models.CharField(max_length=8, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.configuration.models.image_directory_path)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'laboratorio',
                'verbose_name_plural': 'laboratorios',
                'db_table': 'laboratory',
                'ordering': ['id'],
                'permissions': (('view_laboratory', 'Ver laboratorios'), ('add_laboratory', 'Crear laboratorio'), ('delete_laboratory', 'Eliminar laboratorio'), ('change_laboratory', 'Modificar laboratorio')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('tax', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='impuesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('type_tax', models.CharField(choices=[('General', 'General'), ('Pagos', 'Pagos')], default='General', max_length=25, verbose_name='Tipo de impuesto')),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'impuesto',
                'verbose_name_plural': 'impuestos',
                'db_table': 'tax',
                'permissions': (('view_tax', 'Ver impuestos'), ('add_tax', 'Crear impuesto'), ('delete_tax', 'Eliminar impuesto'), ('change_tax', 'Modificar impuesto')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.laboratory', verbose_name='laboratorio')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
                'db_table': 'cash_register',
                'permissions': (('view_cash_register', 'Ver caja'), ('add_cash_register', 'Crear caja'), ('delete_cash_register', 'Eliminar caja'), ('change_cash_register', 'Modificar caja')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=5)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('type_currency', models.CharField(blank=True, choices=[('Principal', 'Principal'), ('Secundaria', 'Secundaria')], max_length=10, null=True, verbose_name='clasificación')),
                ('is_foreign', models.BooleanField(default=False)),
                ('with_tax', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='configuration.tax')),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'db_table': 'currency',
                'permissions': (('view_currency', 'Ver monedas'), ('add_currency', 'Crear moneda'), ('delete_currency', 'Eliminar moneda'), ('change_currency', 'Modificar moneda')),
                'default_permissions': (),
            },
        ),
    ]
