# Generated by Django 5.0.3 on 2024-11-21 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Devuelto', 'Devuelto'), ('Rechazado', 'Rechazado')], default='Aprobado', max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('operation', models.CharField(blank=True, max_length=255)),
                ('operation_code', models.CharField(blank=True, max_length=25)),
                ('approval_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'aprobación',
                'verbose_name_plural': 'aprobaciones',
                'db_table': 'approvals',
                'permissions': (('view_approvals', 'Ver aprobaciones'), ('approve_purchase_requisition', 'Aprobar requisiciones de compra'), ('approve_purchase_order', 'Aprobar ordenes de compra')),
                'default_permissions': (),
            },
        ),
    ]
