# Generated by Django 5.0.3 on 2024-11-21 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
