# Generated by Django 5.0.3 on 2024-11-21 01:33

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('names', models.CharField(blank=True, max_length=80)),
                ('last_names', models.CharField(blank=True, max_length=80)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('cedula', models.CharField(blank=True, max_length=8)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.TextField(blank=True)),
                ('image', models.ImageField(default='users/avatar_default.jpg', null=True, upload_to=apps.users.models.image_directory_path)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_reset_token', models.TextField(blank=True, null=True)),
                ('cash_register', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_cash_register', to='configuration.cashregister')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_users', to='configuration.laboratory')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'user',
                'permissions': (('view_user', 'Ver Usuarios'), ('add_user', 'Crear Usuario'), ('delete_user', 'Eliminar Usuario'), ('change_user', 'Modificar Usuario')),
                'default_permissions': (),
            },
            managers=[
                ('objects', apps.users.models.CustomUserManager()),
            ],
        ),
    ]
