# Generated by Django 5.0.3 on 2024-11-21 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beginninginventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beginninginventorydetail',
            name='beginning_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beginning_inventory_set', to='inventory.beginninginventory'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.laboratory'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuration.laboratory'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustmentdetail',
            name='inventory_adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryadjustment'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_item_set', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='beginninginventorydetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='adjustmentdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.measureunit'),
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.model'),
        ),
    ]
